ktor:
    application:
        modules:
            - com.anshtya.jetx.server.ApplicationKt.module
    deployment:
        port: 8080

jwt:
    secret: $SECRET
    issuer: "http://127.0.0.1:8080"
    realm: "Access to server"
